//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Employee
    {
        public int TitleCode { get; set; }
        public string TitleName { get; set; }
        public string FirstName { get; set; }
        public string FullName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public string NicNumber { get; set; }
        public int MaritalStatusCode { get; set; }
        public string MaritalStatusName { get; set; }
        public int GenderCode { get; set; }
        public string GenderName { get; set; }
        public System.DateTime CNICExpiryDate { get; set; }
        public int NationalityCode { get; set; }
        public string NationalityName { get; set; }
        public int ReligionCode { get; set; }
        public string ReligionName { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeNumber { get; set; }
        public string AttendanceID { get; set; }
        public int BankCode { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public int BranchCode { get; set; }
        public string BranchName { get; set; }
        public decimal ApprovedSalary { get; set; }
        public string Email { get; set; }
        public int ShiftCode { get; set; }
        public string ShiftName { get; set; }
        public int JobCategoryCode { get; set; }
        public string JobCategoryName { get; set; }
        public System.DateTime DateOfAppointment { get; set; }
        public int DesignationCode { get; set; }
        public string DesignationName { get; set; }
        public int GradeCode { get; set; }
        public string GradeName { get; set; }
        public string ResidentalAddress { get; set; }
        public string ResidentalCity { get; set; }
        public string ResidentalCountry { get; set; }
        public string MobileNumber { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string RelationName { get; set; }
        public string RelationType { get; set; }
        public int EmploymentTypeCode { get; set; }
        public string EmploymentTypeName { get; set; }
        public int LocationCode { get; set; }
        public string LocationName { get; set; }
        public int GeolocationCode { get; set; }
        public string GeolocationName { get; set; }
        public int ReportingDesignationCode { get; set; }
        public string ReportingDesignationName { get; set; }
        public int ReportingPersonCode { get; set; }
        public string ReportingPersonName { get; set; }
        public int Level1Code { get; set; }
        public string Level_1_Group_Company_ { get; set; }
        public int Level2Code { get; set; }
        public string Level_2__Unit_ { get; set; }
        public int Level3Code { get; set; }
        public string Level_3__Sub_Unit_ { get; set; }
        public int Level4Code { get; set; }
        public string Level_4___Function { get; set; }
        public int Level5Code { get; set; }
        public string Level_5___Department { get; set; }
        public int Level6Code { get; set; }
        public string Level_6___Sub_Department { get; set; }
        public int Level7Code { get; set; }
        public string Level_7___Section { get; set; }
        public int Level8Code { get; set; }
        public string Level_8___Machine___Line___Area { get; set; }
        public int JoinedDesignationCode { get; set; }
        public string JoinedDesignationName { get; set; }
        public string ExtensionNo_ { get; set; }
        public System.DateTime ConfirmationDate { get; set; }
        public System.DateTime ResignedDate { get; set; }
        public string CreatedByCode { get; set; }
        public string CreatedByName { get; set; }
        public string Status { get; set; }
    }
}
